// Question texts by id. Keep in sync with the `questions` array in onboarding.html.
// Follow-up questions (ids ending in `_f`) are generated by Gemini at runtime.
export const QUESTIONS = {
  // Deep interview (kept in sync with `questions` in onboarding.html).
  q1: 'Розкажи про мить за останній рік, коли ти відчув(-ла) себе по-справжньому живим(-ою). Де ти був(-ла), з ким, і що робило її справжньою?',
  q2: 'Коли близька людина тебе розчаровує — що відбувається всередині тебе першої хвилини, і як ти зазвичай дієш далі?',
  q3: 'Що людина має зробити чи сказати, щоб ти відчув(-ла): «ось із цим я можу бути собою»?',
  q4: 'За що тебе по-справжньому цінують ті, хто знає тебе давно, — і чи згоден(-на) ти з ними?',
  q5: 'Чого ти більше не готовий(-а) терпіти у стосунках — і що навчило тебе цій межі?',
  // Legacy ids kept for older stored answers.
  q6: 'Згадай момент, коли ти відчував(-ла) себе по-справжньому щасливим(-ою). Що тоді відбувалось?',
  q7: 'Що тобі найбільше потрібно від партнера, коли тобі важко?',
  // Deepen-mode extras (onboarding.html?mode=deepen) — also deep, premium.
  d1: 'Що в тобі змінилося за останні кілька років — і як ти до цього ставишся?',
  d2: 'Яка твоя маленька дивакуватість, яку по-справжньому оцінить лише правильна людина?',
  d3: 'Коли ти уявляєш спільне майбутнє з кимось — що в цій картині для тебе найважливіше?',
  d4: 'У який момент ти відчуваєш найбільшу самотність — і що допомагає з неї вийти?',
  d5: 'Що ти зрозумів(-ла) про кохання таке, чого не знав(-ла) у 20?',
};

export function questionLabel(questionId) {
  if (QUESTIONS[questionId]) return QUESTIONS[questionId];
  if (questionId.endsWith('_f')) {
    const base = QUESTIONS[questionId.slice(0, -2)];
    return base ? `Уточнення до: ${base}` : 'Уточнююче підпитання';
  }
  return questionId;
}
