// Question texts by id. Keep in sync with the `questions` array in onboarding.html.
// Follow-up questions (ids ending in `_f`) are generated by Gemini at runtime.
export const QUESTIONS = {
  q1: 'Опиши свій ідеальний будній вечір — з ким ти і що відбувається?',
  q2: 'Ти більше живеш за чітким планом чи любиш спонтанність? Розкажи на прикладі.',
  q3: 'Що в людях чи в стосунках дратує тебе найбільше?',
  q4: 'Коли виникає конфлікт — ти одразу говориш про це, береш паузу подумати чи мовчиш?',
  q5: 'Що для тебе означає справжня близькість з людиною?',
  q6: 'Згадай момент за останній рік, коли ти відчував(-ла) себе по-справжньому щасливим(-ою). Що тоді відбувалось?',
  q7: 'Що тобі найбільше потрібно від партнера, коли тобі важко?',
};

export function questionLabel(questionId) {
  if (QUESTIONS[questionId]) return QUESTIONS[questionId];
  if (questionId.endsWith('_f')) {
    const base = QUESTIONS[questionId.slice(0, -2)];
    return base ? `Уточнення до: ${base}` : 'Уточнююче підпитання';
  }
  return questionId;
}
