// Question texts by id. Keep in sync with the `questions` array in onboarding.html.
// Follow-up questions (ids ending in `_f`) are generated by Gemini at runtime.
export const QUESTIONS = {
  // Deep interview (kept in sync with `questions` in onboarding.html).
  q1: 'Розкажи про мить за останній рік, коли ти відчув(-ла) себе по-справжньому живим(-ою). Де ти був(-ла), з ким, і що робило її справжньою?',
  q2: 'Коли близька людина тебе розчаровує — що відбувається всередині тебе першої хвилини, і як ти зазвичай дієш далі?',
  q3: 'Що людина має зробити чи сказати, щоб ти відчув(-ла): «ось із цим я можу бути собою»?',
  q4: 'За що тебе по-справжньому цінують ті, хто знає тебе давно, — і чи згоден(-на) ти з ними?',
  q5: 'Чого ти більше не готовий(-а) терпіти у стосунках — і що навчило тебе цій межі?',
  // Legacy ids kept for older stored answers.
  q6: 'Згадай момент, коли ти відчував(-ла) себе по-справжньому щасливим(-ою). Що тоді відбувалось?',
  q7: 'Що тобі найбільше потрібно від партнера, коли тобі важко?',
  // Deepen-mode extras (onboarding.html?mode=deepen) — also deep, premium.
  d1: 'Що в тобі змінилося за останні кілька років — і як ти до цього ставишся?',
  d2: 'Яка твоя маленька дивакуватість, яку по-справжньому оцінить лише правильна людина?',
  d3: 'Коли ти уявляєш спільне майбутнє з кимось — що в цій картині для тебе найважливіше?',
  d4: 'У який момент ти відчуваєш найбільшу самотність — і що допомагає з неї вийти?',
  d5: 'Що ти зрозумів(-ла) про кохання таке, чого не знав(-ла) у 20?',
};

export function questionLabel(questionId) {
  if (QUESTIONS[questionId]) return QUESTIONS[questionId];
  if (questionId.endsWith('_f')) {
    const base = QUESTIONS[questionId.slice(0, -2)];
    return base ? `Уточнення до: ${base}` : 'Уточнююче підпитання';
  }
  return questionId;
}

// --- Is this answer worth a follow-up? --------------------------------------
//
// Every follow-up is a billed model call (PRIV-1 moved them to Anthropic on
// 2026-08-05), and up to five fire per onboarding — the most frequent AI call in
// the product. But cost is only half the reason to skip some of them: a
// follow-up to "не знаю" cannot go deeper, because there is nothing to go deeper
// INTO. The model produces a generic probe, the user feels unheard, and we paid
// for it. Skipping is both cheaper and better.
//
// The bar is deliberately LOW and biased toward asking. This is meant to catch
// «ок», «нормально», «хз» — never a short but real answer. "Коли я втратив
// батька" is four words and matters enormously; it must still get a follow-up.
// When in doubt, ask: a wasted call costs a fraction of a cent, a missed
// follow-up costs interview depth, which is the actual product.
const NON_ANSWERS = new Set([
  'ок', 'окей', 'ok', 'okay', 'да', 'так', 'ні', 'нет', 'no', 'yes',
  'не знаю', 'незнаю', 'хз', 'idk', 'dunno', 'нормально', 'норм', 'nothing',
  'нічого', 'ничего', 'все', 'всё', 'good', 'fine', 'ничего особенного',
]);

/** True when an answer has enough substance that a follow-up can go deeper. */
export function worthFollowingUp(answerText) {
  const raw = String(answerText || '').trim();
  if (!raw) return false;

  // Strip punctuation/emoji for the comparison, but measure the ORIGINAL length —
  // a long answer full of commas is still a long answer.
  const normalized = raw.toLowerCase().replace(/[.!?,;:—–\-()"'«»]/g, ' ').replace(/\s+/g, ' ').trim();
  if (!normalized) return false;
  if (NON_ANSWERS.has(normalized)) return false;

  const words = normalized.split(' ').filter(Boolean).length;
  if (raw.length < 12) return false;              // too short to hold a thought
  if (words < 3 && raw.length < 25) return false; // one long word is not an answer
  return true;
}
